name: React PR Pipeline

on: [workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install --force
    - name: Build
      run: npm run build --if-present
    - name: Run Tests
      run: npm test -- --coverage --passWithNoTests
      
  lint:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install --force
    - name: Prettier
      run: npx pretty-quick --staged
    - name: ESLint
      run: npx eslint src/ --fix
